name: Tests-1

on:
  push:
    branches: [ "main" ]
    paths: [ "1/src/**", ".github/workflows/test-1.yml" ]
  pull_request:
    paths: [ "1/src/**", ".github/workflows/test-1.yml" ]

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./1/src/
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Test lincheck
        run: go test -v ./stack/lincheck/

      - name: Test stacks with lincheck
        run: go test -v ./stack/threadsave/

      - name: Test stacks with race
        run: go test -v --race ./stack/threadsave/